'use strict';
// Physical input adapters and context barriers. Simulation continues to consume game actions.
const DeadwalkInput=(()=>{
 const buttons={CONFIRM:0,CANCEL:1,INTERACT:2,NEXT_WEAPON:3,SWITCH_CHARACTER:4,GRENADE:5,SHOVE:6,FIRE:7,VIEW:8,PAUSE:9,FLASHLIGHT:10,CROUCH:11,NAV_UP:12,NAV_DOWN:13,NAV_LEFT:14,NAV_RIGHT:15};
 const names=['A','B','X','Y','LB','RB','LT','RT','Select','Start','L3','R3','D-pad Up','D-pad Down','D-pad Left','D-pad Right'];
 const bindings={LEFT:['KeyA','ArrowLeft'],RIGHT:['KeyD','ArrowRight'],JUMP:['Space','KeyW','ArrowUp'],RELOAD:['KeyR'],SHOVE:['KeyF'],INTERACT:['KeyE'],HEAL:['KeyH'],BUILD:['KeyQ'],GRENADE:['KeyG','KeyT'],CROUCH:['ControlLeft','ControlRight','KeyC']};
 const extraBindings={FLASHLIGHT:['KeyL'],VOICE:['KeyX'],SWITCH_CHARACTER:['Tab'],PILLS:['Digit4'],ADRENALINE:['Digit5'],KIT:['Digit6'],PAUSE:['Escape'],SOUND:['KeyM']};Object.assign(bindings,extraBindings);const defaultBindings=JSON.parse(JSON.stringify(bindings)),defaultPad={...buttons,RELOAD:-1},padBindings={...defaultPad};let customPad=false;try{const saved=JSON.parse(localStorage.getItem('deadwalk-bindings')||'{}');for(const action of Object.keys(bindings))if(Array.isArray(saved.keyboard?.[action])&&saved.keyboard[action].length===1&&/^(Key[A-Z]|Digit[0-9]|Space|Tab|Escape|Arrow(Left|Right|Up|Down)|Control(Left|Right)|Shift(Left|Right))$/.test(saved.keyboard[action][0]))bindings[action]=saved.keyboard[action];customPad=saved.customPad===true;const values=Object.values(saved.pad||{});if(values.filter(v=>v>=0).length===new Set(values.filter(v=>v>=0)).size)for(const action of Object.keys(padBindings))if(Number.isInteger(saved.pad?.[action])&&saved.pad[action]>=-1&&saved.pad[action]<=11)padBindings[action]=saved.pad[action];}catch{}let captureAction=null,controlsBox=null,controlsReturn=null;
 const keyboard={keys:new Set(),read(){const out={};for(const [action,codes] of Object.entries(bindings))out[action]=codes.some(k=>this.keys.has(k));return out;}},mouse={x:innerWidth*.65,y:innerHeight*.5,down:false};
 const defaults={deadzone:.18,sensitivity:1,acceleration:false,layout:'auto',preset:'auto',dpad:'auto',safeBack:'F8'};let settings={...defaults};try{const saved=JSON.parse(localStorage.getItem('deadwalk-input')||'{}');if([.15,.18,.2,.25].includes(saved.deadzone))settings.deadzone=saved.deadzone;if([.7,1,1.4,2].includes(saved.sensitivity))settings.sensitivity=saved.sensitivity;if(typeof saved.acceleration==='boolean')settings.acceleration=saved.acceleration;if(['auto','classic','deck'].includes(saved.preset))settings.preset=saved.preset;if(['F8','F9','off'].includes(saved.safeBack))settings.safeBack=saved.safeBack;if(['auto','move','shortcuts'].includes(saved.dpad))settings.dpad=saved.dpad;if(['auto','standard'].includes(saved.layout))settings.layout=saved.layout;}catch{}
 const deckPad={...defaultPad,CONFIRM:10,INTERACT:0,RELOAD:2,VIEW:-1,FLASHLIGHT:8};function deckLayout(){return settings.preset==='deck'||settings.preset==='auto'&&/steam|valve|deck/i.test(pad?.id||'');}function applyPreset(){if(!customPad)Object.assign(padBindings,deckLayout()?deckPad:defaultPad);refreshBindings();}function dpadMovement(){return settings.dpad==='move'||settings.dpad==='auto'&&deckLayout();}
 const stats={backActions:0,suppressions:0,connectionEvents:0};
 let everConnected=false;
 let callbacks={},pad=null,padKey=null,previous=[],rawHeld=[],held=[],pressed=[],released=[],blocked=new Set(),context=null,device='keyboard',suspended=false,debug=false,debugBox=null,debugReturn=null,debugTime=0,lastPhysical='None',lastAction='None',lastSuppression='None',lastCancel={time:-Infinity,source:''},mouseBackHeld=false;
 let lastAxes=[];const navHeld=new Set();
 const snapshot={context:'MENU',mapping:'none',pad:null,left:{x:0,y:0,magnitude:0},right:{x:0,y:0,magnitude:0},held:()=>false,pressed:()=>false,released:()=>false,holdSource:()=>false};
 const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
 function radial(x=0,y=0,d=settings.deadzone){x=Number.isFinite(x)?x:0;y=Number.isFinite(y)?y:0;const length=Math.hypot(x,y);if(length<=d)return{x:0,y:0,magnitude:0};const magnitude=clamp((Math.min(length,1)-d)/(1-d),0,1);return{x:x/length*magnitude,y:y/length*magnitude,magnitude};}
 function editable(target){return target instanceof Element&&!!target.closest('input:not([type="button"]):not([type="range"]),textarea,[contenteditable]:not([contenteditable="false"])');}
 function owns(target=document.activeElement){if(suspended||!document.hasFocus()||document.hidden||editable(target))return false;if(!target||target===document.body||target===document.documentElement)return true;return target instanceof Element&&!!target.closest('#game,.overlay,#voice-menu,#controller-choice,#controller-debug,#switch-character,#auto-use-items,#touch-controls');}
 function currentContext(){return debug?'CONTROLLER_DEBUG':callbacks.context?.()||'MENU';}
 function log(message){if(debug)console.info('[INPUT] '+message);}
 function setDevice(value){if(device===value)return;device=value;document.body.classList.toggle('controller-menu',value==='gamepad');callbacks.device?.(value);log('Active input = '+value);}
 function configure(value){callbacks=value;}
 function actionName(index,ctx=currentContext()){if(ctx==='GAMEPLAY'){const a=Object.keys(padBindings).find(k=>padBindings[k]===index);return a==='CONFIRM'?'JUMP':a==='CANCEL'?'HEAL':a||'UNASSIGNED';}if(index===1)return 'CANCEL';if(index===0)return 'CONFIRM';if(index===8)return 'SWITCH_CHARACTER';if(index>=12)return ctx==='GAMEPLAY'?'D_PAD_SHORTCUT':'NAVIGATE';return Object.keys(ctx==='GAMEPLAY'?padBindings:buttons).find(k=>(ctx==='GAMEPLAY'?padBindings:buttons)[k]===index)||'UNASSIGNED';}
 function back(source){const now=performance.now();if(source!==lastCancel.source&&now-lastCancel.time<140&&rawHeld[1]&&(source==='gamepad'||lastCancel.source==='gamepad'))return;lastCancel={source,time:now};stats.backActions++;const backIndex=currentContext()==='GAMEPLAY'?padBindings.CANCEL:1;lastPhysical=source==='gamepad'?'Button '+backIndex+' / '+names[backIndex]:source;lastAction=currentContext()==='GAMEPLAY'&&!deckLayout()&&!source.startsWith('Rear-button key ')?'HEAL':'CANCEL';log(`B/back pressed · Context = ${currentContext()} · Action = ${lastAction}`);if(debug){setDebug(false);return;}if(source.startsWith('Rear-button key '))callbacks.safeBack?.(source);else callbacks.cancel?.(source);}
 function poll(){let pads=[];try{pads=Array.from(navigator.getGamepads?.()||[]).filter(p=>p&&p.connected!==false);}catch(e){log('Gamepad API unavailable: '+e.name);}const next=pads.find(p=>`${p.index}:${p.id||''}`===padKey)||pads.find(p=>p.buttons?.some(b=>b.pressed||b.value>.5)||p.axes?.some(a=>Math.abs(a)>.35))||pads[0]||null;
 const key=next?`${next.index}:${next.id||''}`:null,changed=key!==padKey;pad=next;padKey=key;if(changed)applyPreset();const firstConnection=!!pad&&!everConnected;if(pad)everConnected=true;if(changed){previous=[];blocked.clear();if(pad&&!firstConnection)for(let i=0;i<(pad.buttons?.length||0);i++)if(pad.buttons[i].pressed||pad.buttons[i].value>.5)blocked.add(i);if(!pad)setDevice('keyboard');callbacks.connection?.(pad);log(pad?'Gamepad connected: '+(pad.id||'unnamed'):'Gamepad disconnected');if(/steam|valve|deck/i.test(pad?.id||''))log('Steam Deck / Steam Input detected');}
 const priorRaw=rawHeld;rawHeld=pad?Array.from(pad.buttons||[],b=>!!b.pressed||(b.value||0)>.5):[];if(priorRaw[1]&&!rawHeld[1])lastCancel.time=-Infinity;const ctx=currentContext(),focused=owns();if(context!==ctx||!focused){for(let i=0;i<rawHeld.length;i++)if(rawHeld[i]&&(!focused||priorRaw[i]))blocked.add(i);if(context!==ctx)log('Context = '+ctx);context=ctx;}
 // First observed controller may already contain the user's discovery press.
 if(firstConnection&&snapshot.context===ctx&&focused)blocked.clear();
 for(const i of blocked)if(!rawHeld[i])blocked.delete(i);const mapping=pad?(pad.mapping==='standard'?'standard':'unknown'):'none',supported=mapping==='standard'||settings.layout==='standard';held=rawHeld.map((v,i)=>v&&focused&&supported&&!blocked.has(i));pressed=held.map((v,i)=>v&&!previous[i]);released=previous.map((v,i)=>v&&!held[i]);previous=[...held];
 Object.assign(snapshot,{context:ctx,mapping,pad,left:focused&&supported?radial(pad?.axes?.[0],pad?.axes?.[1]):radial(),right:focused&&supported?radial(pad?.axes?.[2],pad?.axes?.[3]):radial(),held:a=>!!held[(ctx==='GAMEPLAY'?padBindings:buttons)[a]],pressed:a=>!!pressed[(ctx==='GAMEPLAY'?padBindings:buttons)[a]],released:a=>!!released[(ctx==='GAMEPLAY'?padBindings:buttons)[a]],holdSource:a=>focused&&supported&&!!rawHeld[(ctx==='GAMEPLAY'?padBindings:buttons)[a]]});
 const axes=pad?.axes||[];if(focused&&!pressed.some(Boolean)){if(Math.abs((axes[2]||0)-(lastAxes[2]||0))>.08||Math.abs((axes[3]||0)-(lastAxes[3]||0))>.08){lastPhysical='Right stick';lastAction='LOOK';}else if(Math.abs((axes[0]||0)-(lastAxes[0]||0))>.08||Math.abs((axes[1]||0)-(lastAxes[1]||0))>.08){lastPhysical='Left stick';lastAction='MOVE';}}lastAxes=Array.from(axes);if(focused&&supported&&(pressed.some(Boolean)||snapshot.left.magnitude>.12||snapshot.right.magnitude>.12))setDevice('gamepad');for(let i=0;i<pressed.length;i++)if(pressed[i]){lastPhysical=`Button ${i} / ${names[i]||i}`;lastAction=actionName(i,ctx);log(`${names[i]} pressed · Context = ${ctx} · Action = ${lastAction}`);}updateDebug();return snapshot;}
 function gameplay(currentAngle,dt=1/60){if(snapshot.context!=='GAMEPLAY'||currentContext()!=='GAMEPLAY'||!owns())return {};let angle=null;if(snapshot.right.magnitude){const target=Math.atan2(snapshot.right.y,snapshot.right.x),delta=Math.atan2(Math.sin(target-currentAngle),Math.cos(target-currentAngle)),speed=settings.sensitivity*80*(settings.acceleration?.35+.65*snapshot.right.magnitude:1);angle=currentAngle+delta*(1-Math.exp(-speed*dt));}return {move:snapshot.left.magnitude?snapshot.left.x:dpadMovement()?Number(snapshot.held('NAV_RIGHT'))-Number(snapshot.held('NAV_LEFT')):0,angle,fire:snapshot.held('FIRE'),jump:snapshot.held('CONFIRM'),use:snapshot.held('INTERACT'),shove:snapshot.held('SHOVE'),grenade:snapshot.held('GRENADE'),crouch:snapshot.held('CROUCH')};}
 function saveSetting(key,value){settings[key]=value;try{localStorage.setItem('deadwalk-input',JSON.stringify(settings));}catch{}for(const select of document.querySelectorAll(`[data-input="${key}"]`))select.value=String(value);}
 function setDebug(value){debug=!!value;for(const select of document.querySelectorAll('[data-input="debug"]'))select.value=debug?'on':'off';if(debug){debugReturn=document.activeElement;callbacks.debugOpen?.();if(!debugBox){debugBox=document.createElement('section');debugBox.id='controller-debug';debugBox.setAttribute('role','dialog');debugBox.setAttribute('aria-label','Controller diagnostics');const title=document.createElement('h2');title.textContent='CONTROLLER DEBUG';const pre=document.createElement('pre');const grid=document.createElement('div');grid.className='debug-buttons';names.forEach((name,i)=>{const b=document.createElement('span');b.dataset.debugButton=i;b.textContent=name;grid.append(b);});const close=document.createElement('button');close.textContent='CLOSE · B / ESC / F4';close.onclick=()=>setDebug(false);debugBox.append(title,pre,grid,close);document.body.append(debugBox);}debugBox.hidden=false;debugBox.querySelector('button').focus();debugTime=0;log('Controller debug enabled');updateDebug();}else{if(debugBox)debugBox.hidden=true;debugReturn?.focus();}}
 function updateDebug(){if(!debug||!debugBox||performance.now()-debugTime<90)return;debugTime=performance.now();const lines=[`Controller: ${pad?.id||'Not exposed / disconnected'}`,`Gamepad index: ${pad?.index??'none'}`,`Layout: ${deckLayout()?'Steam Deck':'Original'} · D-pad: ${dpadMovement()?'movement':'shortcuts'}`,`Mapping: ${snapshot.mapping}${snapshot.mapping==='unknown'?' (choose Standard layout only for compatible pads)':''}`,`Context: ${currentContext()} · Input: ${device}`,`Safe Back key: ${settings.safeBack}`,`Focused: ${owns()} · API: ${!!navigator.getGamepads}`,`Physical: ${lastPhysical}`,`Game action: ${lastAction}`,`Navigation: ${lastSuppression}`,'',...names.map((name,i)=>`${name.padEnd(7)} ${(pad?.buttons?.[i]?.value||0).toFixed(2)}  ${pressed[i]?'PRESSED':released[i]?'RELEASED':held[i]?'HELD':'-'}`),'',`Left X/Y: ${(pad?.axes?.[0]||0).toFixed(3)} / ${(pad?.axes?.[1]||0).toFixed(3)}`,`Right X/Y: ${(pad?.axes?.[2]||0).toFixed(3)} / ${(pad?.axes?.[3]||0).toFixed(3)}`,`Deadzone ${settings.deadzone} · Sensitivity ${settings.sensitivity}`];debugBox.querySelector('pre').textContent=lines.join('\n');for(const b of debugBox.querySelectorAll('[data-debug-button]')){const i=Number(b.dataset.debugButton);b.classList.toggle('active',!!rawHeld[i]);b.textContent=names[i]+' '+(pad?.buttons?.[i]?.value||0).toFixed(2);}}
 function suppress(e,signal){if(!owns(e.target)||!e.cancelable)return false;e.preventDefault();e.stopImmediatePropagation();stats.suppressions++;lastSuppression=signal+' · suppression attempted';log('Browser navigation suppression attempted: '+signal);return true;}
 addEventListener('keydown',e=>{if(!captureAction)return;e.preventDefault();e.stopImmediatePropagation();if(e.repeat)return;if(e.code==='Escape'||settings.safeBack!=='off'&&e.code===settings.safeBack){captureAction=null;refreshBindings();return;}if(!/^(Key[A-Z]|Digit[0-9]|Space|Tab|Arrow(Left|Right|Up|Down)|Control(Left|Right)|Shift(Left|Right))$/.test(e.code)){controlsBox.querySelector('[data-binding-status]').textContent='Choose a letter, number, arrow, Space, Tab, Ctrl or Shift.';return;}const action=captureAction,old=bindings[action];for(const other of Object.keys(bindings))if(other!==action&&bindings[other].includes(e.code))bindings[other]=[old[0]];bindings[action]=[e.code];captureAction=null;saveBindings();controlsBox.querySelector('[data-binding-status]').textContent='Saved. Conflicting keys are swapped automatically.';},true);
 addEventListener('keydown',e=>{if(settings.safeBack!=='off'&&e.code===settings.safeBack&&owns(e.target)&&e.cancelable){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat&&!navHeld.has(e.code)){navHeld.add(e.code);back('Rear-button key '+e.code);}return;}if(e.code==='F4'&&owns(e.target)){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)setDebug(!debug);return;}const alias=e.key==='BrowserBack'||e.code==='BrowserBack'||e.code==='Backspace'||e.altKey&&!e.ctrlKey&&!e.metaKey&&e.code==='ArrowLeft';if(alias&&suppress(e,e.altKey?'Alt+Left':e.code||e.key)){if(!e.repeat&&!navHeld.has(e.code)){navHeld.add(e.code);back('keyboard navigation');}return;}if(e.code==='Escape'&&['DIALOG','VOICE_MENU','CONTROLLER_DEBUG','PAUSED','CONTROLS'].includes(currentContext())&&suppress(e,'Escape cancel')){if(!e.repeat)back('keyboard Escape');return;}if(owns(e.target)){setDevice('keyboard');if(!e.repeat){lastPhysical='Keyboard '+e.code;lastAction=Object.keys(bindings).find(a=>matches(a,e.code))||'MENU / KEYBOARD';}}},true);
 addEventListener('keyup',e=>{if(navHeld.has(e.code)){navHeld.delete(e.code);suppress(e,e.code+' release');}},true);
 for(const type of ['pointerdown','mousedown','pointerup','mouseup','auxclick'])addEventListener(type,e=>{if(e.button!==3||!suppress(e,'mouse Back'))return;if(type==='pointerdown'||type==='mousedown'){if(!mouseBackHeld){mouseBackHeld=true;back('mouse navigation');}}else if(type==='pointerup'||type==='mouseup')mouseBackHeld=false;},true);
 addEventListener('pointerdown',e=>{if(owns(e.target)){setDevice(e.pointerType==='touch'?'touch':'keyboard');lastPhysical='Pointer button '+e.button;lastAction=e.button===0?'FIRE / CONFIRM':'POINTER';}},true);
 addEventListener('pointermove',e=>{if((e.movementX||e.movementY)&&owns(e.target)){setDevice(e.pointerType==='touch'?'touch':'keyboard');if(debug){lastPhysical='Pointer / mouse movement';lastAction='LOOK';}}},true);
 addEventListener('blur',()=>{suspended=true;keyboard.keys.clear();mouse.down=false;mouseBackHeld=false;navHeld.clear();});addEventListener('focus',()=>{suspended=false;});
 addEventListener('gamepadconnected',e=>{stats.connectionEvents++;log('Gamepad connection event: '+e.gamepad.id);callbacks.connectionEvent?.(e.gamepad,true);});addEventListener('gamepaddisconnected',e=>{stats.connectionEvents++;log('Gamepad disconnection event: '+e.gamepad.id);callbacks.connectionEvent?.(e.gamepad,false);});
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen({navigationUI:'hide'});else throw Error('Fullscreen unavailable');for(const status of document.querySelectorAll('.input-status'))status.textContent='';}catch{for(const status of document.querySelectorAll('.input-status'))status.textContent='Fullscreen needs browser permission and a click, tap or keyboard Enter. The game remains playable here.';}}
 function refreshMenuActions(){for(const b of document.querySelectorAll('[data-controller-health]'))b.textContent='AUTO HEALTH ITEMS: '+(document.getElementById('auto-use-items').getAttribute('aria-pressed')==='true'?'ON':'OFF');for(const b of document.querySelectorAll('[data-controller-sound]'))b.textContent=document.getElementById('sound').textContent.replace(/^M /,'');}
 function setupMenus(){for(const panel of document.querySelectorAll('.overlay .panel')){const host=document.createElement('details');host.className='controller-settings input-settings';const title=document.createElement('summary');title.textContent='CONTROLLER OPTIONS / DEBUG';host.append(title);for(const [key,labelText,options] of [['deadzone','Stick deadzone',{'0.15':'0.15','0.18':'0.18 (default)','0.2':'0.20','0.25':'0.25'}],['sensitivity','Aim sensitivity',{'0.7':'Gentle','1':'Normal','1.4':'Fast','2':'Very fast'}],['acceleration','Aim acceleration',{false:'Off',true:'On'}],['layout','Controller mapping',{auto:'Automatic (standard only)',standard:'Force standard layout'}],['debug','Controller debug',{off:'Off',on:'On'}]]){const label=document.createElement('label');label.textContent=labelText;const select=document.createElement('select');select.dataset.input=key;select.setAttribute('aria-label',labelText);for(const [value,text] of Object.entries(options)){const option=document.createElement('option');option.value=value;option.textContent=text;select.append(option);}select.value=key==='debug'?'off':String(settings[key]);select.onchange=()=>{if(key==='debug')setDebug(select.value==='on');else saveSetting(key,key==='acceleration'?select.value==='true':['deadzone','sensitivity'].includes(key)?Number(select.value):select.value);};label.append(select);host.append(label);}const full=document.createElement('button');full.textContent='ENTER FULLSCREEN';full.dataset.fullscreen='';full.onclick=fullscreen;const status=document.createElement('p');status.className='input-status';status.setAttribute('role','status');const health=document.createElement('button');health.dataset.controllerHealth='';health.textContent='AUTO HEALTH ITEMS: ON';health.onclick=()=>{document.getElementById('auto-use-items').click();refreshMenuActions();};const mute=document.createElement('button');mute.dataset.controllerSound='';mute.textContent='SOUND ON';mute.onclick=()=>callbacks.sound?.();host.append(full,status,health,mute);panel.append(host);}
 document.addEventListener('fullscreenchange',()=>{for(const b of document.querySelectorAll('[data-fullscreen]'))b.textContent=document.fullscreenElement?'EXIT FULLSCREEN':'ENTER FULLSCREEN';});if(new URLSearchParams(location.search).get('controllerDebug')==='1')setDebug(true);}

 function saveBindings(){try{localStorage.setItem('deadwalk-bindings',JSON.stringify({keyboard:bindings,pad:padBindings,customPad}));}catch{}keyboard.keys.clear();refreshBindings();callbacks.bindings?.();}
 const labels={LEFT:'Move left',RIGHT:'Move right',JUMP:'Jump',CONFIRM:'Jump',CANCEL:'Use health',RELOAD:'Reload',SHOVE:'Push / whack',INTERACT:'Pickup / interact',HEAL:'Use health',BUILD:'Build gate',GRENADE:'Throw grenade',CROUCH:'Crouch',FLASHLIGHT:'Flashlight',VOICE:'Voice menu (hold)',SWITCH_CHARACTER:'Switch character',NEXT_WEAPON:'Switch weapon',PILLS:'Use pills',ADRENALINE:'Use adrenaline',KIT:'Use medkit',PAUSE:'Pause',SOUND:'Toggle sound'};
 function keyLabel(code){return code.replace(/^Key/,'').replace(/^Digit/,'').replace('Control','Ctrl ').replace('Arrow','Arrow ').replace('Shift','Shift ');}
 function matches(action,code){return bindings[action]?.includes(code)||false;}
 function refreshBindings(){if(!controlsBox)return;for(const b of controlsBox.querySelectorAll('[data-bind-key]'))b.textContent=captureAction===b.dataset.bindKey?'PRESS A KEY · ESC CANCEL':bindings[b.dataset.bindKey].map(keyLabel).join(' / ');for(const select of controlsBox.querySelectorAll('[data-bind-pad]')){select.value=String(padBindings[select.dataset.bindPad]);if(select.dataset.bindPad==='CANCEL')select.closest('label').firstChild.textContent=deckLayout()?'Cancel / back':'Use health';}}
 function closeControls(){captureAction=null;if(!controlsBox)return;controlsBox.hidden=true;controlsReturn?.focus();refreshBindings();}
 function openControls(button){controlsReturn=button;controlsBox.hidden=false;controlsBox.querySelector('button').focus();}

 function setupControls(){controlsBox=document.createElement('section');controlsBox.id='controls-menu';controlsBox.className='overlay controls-overlay';controlsBox.hidden=true;controlsBox.setAttribute('role','dialog');controlsBox.setAttribute('aria-modal','true');controlsBox.setAttribute('aria-label','Custom controls');const panel=document.createElement('div');panel.className='panel';panel.innerHTML='<div class="eyebrow">MAKE IT YOURS</div><h2>CUSTOM CONTROLS</h2><button data-close-controls>BACK · B / ESC</button><p>Changes save automatically on this device. Select a keyboard action, then press its new key. Controller button conflicts swap automatically. Menu controls stay A confirm, B back, D-pad / left stick navigate, right stick scroll.</p><p data-binding-status role="status"></p>';controlsBox.append(panel);document.body.append(controlsBox);panel.querySelector('[data-close-controls]').onclick=closeControls;for(const [key,title,options] of [['preset','Controller layout',{auto:'Automatic: Steam Deck / Xbox',classic:'Original Xbox / Steam Deck controls',deck:'Steam Deck test layout (A interact, X reload)'}],['dpad','Gameplay D-pad',{auto:'Automatic: movement on Steam Deck',move:'Movement (left / right)',shortcuts:'Health / voice shortcuts'}],['safeBack','Safe Back / rear grip key',{F8:'F8 — bind L4 or R4 in Steam Input',F9:'F9 — alternative rear grip binding',off:'Disabled'}]]){const row=document.createElement('label');row.className='difficulty-label';row.textContent=title;const select=document.createElement('select');select.className='difficulty-select';select.dataset.input=key;for(const [value,text] of Object.entries(options)){const o=document.createElement('option');o.value=value;o.textContent=text;select.append(o);}select.value=settings[key];select.onchange=()=>{saveSetting(key,select.value);if(key==='preset'){customPad=false;applyPreset();saveBindings();}callbacks.bindings?.();};row.append(select);panel.append(row);}const rearHelp=document.createElement('p');rearHelp.className='rear-button-help';rearHelp.textContent='Steam Deck rear-button setup: in Steam Input, enable L4 or R4 and bind it to keyboard F8 (or your selected Safe Back key). It pauses gameplay or goes back one menu level. Rear buttons are configured in Steam Input; the web game cannot assign them directly. Remove B’s Browser Back / Backspace binding there to avoid leaving the page.';panel.append(rearHelp);
 const keysHost=document.createElement('details');keysHost.className='controller-settings';keysHost.innerHTML='<summary>KEYBOARD BINDINGS</summary>';for(const action of Object.keys(bindings)){const row=document.createElement('label');row.textContent=labels[action]||action;const b=document.createElement('button');b.dataset.bindKey=action;b.onclick=()=>{captureAction=action;refreshBindings();};row.append(b);keysHost.append(row);}panel.append(keysHost);
 const padHost=document.createElement('details');padHost.className='controller-settings';padHost.innerHTML='<summary>CONTROLLER BUTTONS</summary>';for(const action of Object.keys(padBindings).filter(a=>!a.startsWith('NAV_')&&a!=='VIEW'&&a!=='PAUSE')){const row=document.createElement('label');row.textContent=labels[action]||action;const select=document.createElement('select');select.dataset.bindPad=action;select.setAttribute('aria-label','Controller '+row.textContent);for(const i of [-1,0,1,2,3,4,5,6,7,8,10,11]){const o=document.createElement('option');o.value=i;o.textContent=i<0?'Unassigned':names[i];select.append(o);}select.onchange=()=>{customPad=true;const value=Number(select.value),old=padBindings[action];for(const other of Object.keys(padBindings))if(other!==action&&value>=0&&padBindings[other]===value)padBindings[other]=old;padBindings[action]=value;saveBindings();};row.append(select);padHost.append(row);}panel.append(padHost);
 for(const host of document.querySelectorAll('#intro .controller-settings'))panel.append(host);const reset=document.createElement('button');reset.textContent='RESET CUSTOM BINDINGS';reset.onclick=()=>{captureAction=null;for(const a of Object.keys(bindings))bindings[a]=[...defaultBindings[a]];customPad=false;applyPreset();saveBindings();panel.querySelector('[data-binding-status]').textContent='Keyboard and controller button defaults restored.';};panel.append(reset);for(const id of ['intro','pause']){const button=document.createElement('button');button.textContent='CONTROLS';button.dataset.openControls='';button.onclick=()=>openControls(button);const target=document.querySelector('#'+id+' .panel');target.querySelector('button').after(button);}refreshBindings();}

 return {scrollDebug:amount=>{if(debugBox)debugBox.scrollTop+=amount;},get deckLayout(){return deckLayout();},get dpadMovement(){return dpadMovement();},buttonLabel:a=>padBindings[a]<0?"Unassigned":names[padBindings[a]],keyLabel:a=>bindings[a]?.map(keyLabel).join(" / "),setupControls,closeControls,matches,get controlsOpen(){return !!controlsBox&&!controlsBox.hidden;},get capturing(){return !!captureAction;},configure,poll,gameplay,back,radial,owns,keyboard,mouse,buttons,snapshot,setupMenus,refreshMenuActions,setDebug,fullscreen,settings,stats,get diagnostics(){return {lastPhysical,lastAction,lastSuppression};},get device(){return device;},get debug(){return debug;}};
})();
