'use strict';
// Canvas light-field renderer. Visibility meshes clip irradiance before it multiplies
// scene materials; opaque world geometry casts shadows instead of a screen overlay.
const DeadwalkLighting=(()=>{
 const presets={low:{scale:.35,lights:5,actors:4,rays:32,soft:0},medium:{scale:.5,lights:8,actors:8,rays:48,soft:1},high:{scale:.7,lights:12,actors:12,rays:64,soft:1},ultra:{scale:1,lights:16,actors:20,rays:88,soft:2}};
 let quality=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent)?'medium':'high',debug=false;try{const saved=localStorage.getItem('deadwalk-light-quality');if(presets[saved])quality=saved;}catch{}
 const field=document.createElement('canvas'),g=field.getContext('2d'),cache=new Map(),pool=[];
 const stats={lights:0,shadows:0,casters:0,renderMs:0,quality,cacheHits:0};
 const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
 function light(id,x,y,r,color,strength=1,extra={}){const l=pool.pop()||{};Object.assign(l,{id,x,y,r,color,strength,angle:null,cone:null,dynamic:false},extra);return l;}
 function sources(f){const lights=[],{run,time}=f;for(const b of DW.FIRE_BARRELS){const drift=Math.sin(time*3+b.phase),flicker=DeadwalkEnvironment.fireProfile(b,time).flicker;lights.push(light('fire-'+b.x,b.x+drift,b.y-49,190*flicker*DeadwalkEnvironment.fireProfile(b,time).size,[255,160+Math.round(drift*4),65],1.55,{dynamic:true,emitter:'barrel-'+b.x}));}
 for(const l of DeadwalkEnvironment.lamps){if(l.state==='dead')continue;const unstable=l.state==='flicker'&&Math.sin(time*.73+l.x)> .93,strength=unstable?.34:1.25;lights.push(light('lamp-'+l.x,l.x+(l.type==='pole'?38:0),l.y+3,l.y>DW.SEWER.streetY?340:l.type==='pole'?355:l.type==='emergency'?180:220,l.type==='emergency'?[255,185,118]:[184,211,218],strength,{angle:Math.PI/2,cone:l.type==='pole'?1.02:1.3}));}
 if(run.sewerHatch)lights.push(light('sewer-hatch',run.sewerHatch.x,run.sewerHatch.y-12,100,[244,248,255],.95,{dynamic:true}));
 lights.push(light('hotel-neon',3210,435,95,[238,100,75],.55));
 for(const r of run.safeRooms)lights.push(light('checkpoint-'+r.id,r.entry+180,548,155,[227,212,156],1.1,{angle:Math.PI/2,cone:1.35}));
 if(run.safeDoor.enabled)lights.push(light('safe-room',run.safeDoor.x+140,634,210,[227,224,175],1.1,{angle:Math.PI/2,cone:1.35}));
 for(const p of run.players){if(p.dead)continue;const origin=DW.weaponOrigin(p);if(p.flashlight&&!p.down&&!p.grab&&!p.carry&&p.weapon!=='pipebomb')lights.push(light('torch-'+p.id,origin.x,origin.y,540,[231,230,208],1.5,{angle:origin.angle,cone:.32,dynamic:true,emitter:'actor-'+p.id}));if(p.flash>0)lights.push(light('muzzle-'+p.id,origin.x,origin.y,145,[255,207,127],2,{dynamic:true,emitter:'actor-'+p.id}));}
 for(const t of run.turrets)if(t.flash>0)lights.push(light('turret-flash-'+t.id,t.x+Math.cos(t.angle)*70,t.y-49+Math.sin(t.angle)*70,180,[255,207,127],2.1,{dynamic:true,emitter:'turret-'+t.id}));for(const car of run.cars)if(car.kind==='police'&&!car.isAlarm&&car.beaconEnabled!==false){const blue=Math.floor(time*2)%2===0;lights.push(light('checkpoint-beacon-'+car.x,car.x+62,car.y-47,105,blue?[89,150,255]:[255,68,52],.8,{dynamic:true,emitter:'car-'+car.x}));}for(const car of run.cars)if(car.alarm>0&&Math.floor(time*5)%2===0)lights.push(light('alarm-'+car.x,car.x+116,car.y-30,90,[255,62,31],.8,{dynamic:true,emitter:'car-'+car.x}));
 if(run.map==='no-mercy'&&run.level!=='rooftop')for(const x of [14948])lights.push(light('service-wing-'+x,x,475,280,[211,222,190],1.3,{angle:Math.PI/2,cone:1.4}));
 if(run.level==='rooftop'&&run.rooftopEncounter.phase==='idle')lights.push(light('radio-highlight',run.rooftopRadio.x,run.rooftopRadio.y-70,100,[255,255,255],1.4,{dynamic:true}));
 if(run.level==='rooftop')for(const x of [15180,15480,15800,16300,16980,17550])lights.push(light('roof-flood-'+x,x+28,run.roofFloor(x)-187,440,[226,236,207],1.9,{angle:Math.PI/2,cone:1.15}));return run.level==='rooftop'?lights.filter(l=>l.x>=15000):lights;}
 function geometry(f,visible,preset){const boxes=DeadwalkEnvironment.occluders(f.run);for(const b of DW.FIRE_BARRELS)boxes.push({id:'barrel-'+b.x,x:b.x-14,y:b.y-39,w:28,h:39});for(const car of f.run.cars){const points=[[car.x-12,car.y-27],[car.x+21,car.y-29],[car.x+40,car.y-50],[car.x+85,car.y-50],[car.x+106,car.y-30],[car.x+138,car.y-23],[car.x+134,car.y],[car.x-7,car.y]];if(car.spin||car.wrecked)for(const p of points){const dx=p[0]-(car.x+62),dy=p[1]-(car.y-24);p[0]=car.x+62+dx*Math.cos((car.spin||0)+(car.wrecked?Math.PI:0))-dy*Math.sin((car.spin||0)+(car.wrecked?Math.PI:0));p[1]=car.y-24+dx*Math.sin((car.spin||0)+(car.wrecked?Math.PI:0))+dy*Math.cos((car.spin||0)+(car.wrecked?Math.PI:0));}const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);boxes.push({id:'car-'+car.x,x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys),points});}const enemies=f.perception?[]:f.run.zombies.filter(z=>z.hp>0&&z.x>f.left-100&&z.x<f.right+100).sort((a,b)=>Math.min(...visible.map(l=>Math.hypot(a.x-l.x,a.y-35-l.y)))-Math.min(...visible.map(l=>Math.hypot(b.x-l.x,b.y-35-l.y))));for(const [i,rock] of f.run.tankRocks.entries())boxes.push({id:'rock-'+i,x:rock.x-28,y:rock.y-17,w:56,h:34,points:[[rock.x-28,rock.y],[rock.x-14,rock.y-17],[rock.x+17,rock.y-13],[rock.x+28,rock.y+5],[rock.x+9,rock.y+17],[rock.x-20,rock.y+12]]});const actors=[...f.run.players.filter(p=>!p.dead),...enemies];for(const a of actors.slice(0,preset.actors)){const h=a.down?16:a.role==='tank'?135:67,w=a.down?34:a.role==='tank'?62:22,top=a.y-h;const points=a.down?[[a.x-w/2,top+6],[a.x+w/2,top],[a.x+w/2,a.y],[a.x-w/2,a.y]]:[[a.x-w*.18,top],[a.x+w*.18,top],[a.x+w*.24,top+8],[a.x+w*.5,top+h*.25],[a.x+w*.35,top+h*.66],[a.x+w*.46,a.y],[a.x+w*.1,a.y],[a.x,top+h*.72],[a.x-w*.18,a.y],[a.x-w*.5,a.y],[a.x-w*.26,top+h*.64],[a.x-w*.5,top+h*.24],[a.x-w*.24,top+8]];boxes.push({id:(a.role?'enemy-':'actor-')+a.id,x:a.x-w/2,y:top,w,h,points,dynamic:true});}for(const p of f.run.players){if(p.dead||p.down)continue;const o=DW.weaponOrigin(p),ex=o.x+Math.cos(o.angle)*18,ey=o.y+Math.sin(o.angle)*18;boxes.push({id:'weapon-'+p.id,x:Math.min(o.x,ex)-2,y:Math.min(o.y,ey)-2,w:Math.abs(ex-o.x)+4,h:Math.abs(ey-o.y)+4,receiverOnly:true,dynamic:true,points:[[o.x-Math.sin(o.angle)*2,o.y+Math.cos(o.angle)*2],[ex-Math.sin(o.angle)*2,ey+Math.cos(o.angle)*2],[ex+Math.sin(o.angle)*2,ey-Math.cos(o.angle)*2],[o.x+Math.sin(o.angle)*2,o.y-Math.cos(o.angle)*2]]});}return boxes.filter(b=>b.x+b.w>f.left-600&&b.x<f.right+600);}
 function segments(boxes,l){const out=[];for(const b of boxes){if(b.receiverOnly)continue;if(b.id===l.emitter||l.x>b.x-2&&l.x<b.x+b.w+2&&l.y>b.y-2&&l.y<b.y+b.h+2)continue;if(b.x>l.x+l.r||b.x+b.w<l.x-l.r||b.y>l.y+l.r||b.y+b.h<l.y-l.r)continue;const points=b.points||[[b.x,b.y],[b.x+b.w,b.y],[b.x+b.w,b.y+b.h],[b.x,b.y+b.h]];for(let i=0;i<points.length;i++)out.push([points[i],points[(i+1)%points.length]]);}return out;}
 function mesh(l,edges,rays){const angles=[];for(let i=0;i<rays;i++)angles.push(i/rays*Math.PI*2);const seen=new Set();for(const [a,b] of edges)for(const v of [a,b]){const key=v.join(',');if(seen.has(key))continue;seen.add(key);const angle=Math.atan2(v[1]-l.y,v[0]-l.x);angles.push(...[angle-.00015,angle,angle+.00015].map(a=>(a+Math.PI*2)%(Math.PI*2)));}angles.sort((a,b)=>a-b);const polygon=[];for(const angle of angles){const dx=Math.cos(angle),dy=Math.sin(angle);let nearest=l.r;for(const [a,b] of edges){const ex=b[0]-a[0],ey=b[1]-a[1],den=dx*ey-dy*ex;if(Math.abs(den)<1e-8)continue;const ax=a[0]-l.x,ay=a[1]-l.y,t=(ax*ey-ay*ex)/den,u=(ax*dy-ay*dx)/den;if(t>.2&&t<nearest&&u>=0&&u<=1)nearest=t;}polygon.push([l.x+dx*nearest,l.y+dy*nearest]);}return polygon;}
 function path(poly){g.beginPath();poly.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.closePath();}
 function irradiance(l,poly,weight=1){g.save();path(poly);g.clip();const [r,green,b]=l.color,strength=l.strength*weight;const gradient=g.createRadialGradient(l.x,l.y,0,l.x,l.y,l.r);const color=a=>`rgba(${r},${green},${b},${clamp(a,0,1)})`;gradient.addColorStop(0,color(strength));gradient.addColorStop(.14,color(strength*.95));gradient.addColorStop(.4,color(strength*.55));gradient.addColorStop(.7,color(strength*(l.id.startsWith('lamp')?.35:.17)));gradient.addColorStop(1,color(0));g.fillStyle=gradient;
 if(l.angle!==null){const steps=18;for(let i=0;i<steps;i++){const a=l.angle-l.cone+i/steps*l.cone*2,bangle=a+l.cone*2/steps,mid=(i+.5)/steps*2-1;g.globalAlpha=Math.pow(Math.max(0,1-mid*mid),2);g.beginPath();g.moveTo(l.x,l.y);g.arc(l.x,l.y,l.r,a,bangle);g.closePath();g.fill();}}else{g.beginPath();g.arc(l.x,l.y,l.r,0,Math.PI*2);g.fill();}g.restore();}
 function receives(l,b,boxes){if(b.id===l.emitter)return true;const tx=clamp(l.x,b.x+.5,b.x+b.w-.5),ty=clamp(l.y,b.y+.5,b.y+b.h-.5),dx=tx-l.x,dy=ty-l.y,d=Math.hypot(dx,dy);if(d>=l.r)return false;if(l.angle!==null){const angle=Math.atan2(dy,dx),delta=Math.atan2(Math.sin(angle-l.angle),Math.cos(angle-l.angle));if(Math.abs(delta)>l.cone+.08)return false;}const ux=dx/(d||1),uy=dy/(d||1);for(const [a,c] of segments(boxes.filter(other=>other!==b&&!(b.receiverOnly&&other.id==='actor-'+b.id.slice(7))),l)){const ex=c[0]-a[0],ey=c[1]-a[1],den=ux*ey-uy*ex;if(Math.abs(den)<1e-8)continue;const ax=a[0]-l.x,ay=a[1]-l.y,t=(ax*ey-ay*ex)/den,u=(ax*uy-ay*ux)/den;if(t>.5&&t<d-.8&&u>=0&&u<=1)return false;}return true;}

 // Approximate a convex receiver's surface normal across its silhouette.
 // The facing edge receives a rim, while the far face retains night ambient.
 function directionalReceiver(l,b,poly){const cx=b.x+b.w/2,cy=b.y+b.h/2,dx=l.x-cx,dy=l.y-cy,d=Math.hypot(dx,dy),nx=dx/(d||1),ny=dy/(d||1),extent=Math.abs(nx)*b.w/2+Math.abs(ny)*b.h/2;const energy=Math.min(.95,l.strength*Math.pow(Math.max(0,1-d/l.r),1.35)*(b.dynamic?.85:.7));if(!energy)return;g.save();path(poly);g.clip();const face=g.createLinearGradient(cx+nx*extent,cy+ny*extent,cx-nx*extent,cy-ny*extent),c=a=>`rgba(${l.color.join(',')},${energy*a})`;face.addColorStop(0,c(1));face.addColorStop(.07,c(.92));face.addColorStop(.24,c(.53));face.addColorStop(.62,c(.14));face.addColorStop(1,c(.025));g.fillStyle=face;g.fillRect(b.x,b.y,b.w,b.h);g.restore();}
 function reflections(ctx,f,meshes){if(quality==='low')return;for(const x of [2785,3130,3400,3655,4055,4430,4810,5270]){if(!DeadwalkEnvironment.detailed(x)||x<f.left-90||x>f.right+90)continue;const y=f.run.floor(x),width=72+(x%31);for(const {l,polygon} of meshes){const d=Math.hypot(l.x-x,l.y-y);if(d>l.r*.92)continue;let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a[1]>y-1)!==(b[1]>y-1)&&x<(b[0]-a[0])*(y-1-a[1])/(b[1]-a[1])+a[0])inside=!inside;}if(!inside)continue;ctx.save();ctx.globalCompositeOperation='screen';ctx.strokeStyle=`rgba(${l.color.join(',')},${.14*Math.pow(1-d/l.r,1.2)})`;for(let i=0;i<9;i++){const span=width*(1-i/12),shift=Math.sin(i*2.4+f.time*1.7+x)*3;ctx.lineWidth=i<3?1.4:.6;ctx.beginPath();ctx.moveTo(x-span/2+shift,y+15+i*2.5);ctx.quadraticCurveTo(x,y+13+i*2.5,x+span/2+shift,y+15+i*2.5);ctx.stroke();}ctx.restore();}}}
 function render(ctx,f){if(f.run?.map!=='no-mercy')return;const start=performance.now(),preset=presets[quality],w=Math.ceil(f.width*preset.scale),h=Math.ceil(f.height*preset.scale);if(field.width!==w||field.height!==h){field.width=w;field.height=h;}g.setTransform(1,0,0,1,0,0);g.globalCompositeOperation='source-over';g.fillStyle='#293b4b';g.fillRect(0,0,w,h);g.setTransform(preset.scale*f.zoom,0,0,preset.scale*f.zoom,-f.left*preset.scale*f.zoom,f.offset*preset.scale);if(f.run.level==='rooftop'){g.fillStyle='#6a8284';g.fillRect(f.left,-1000,f.right-f.left,3000);}g.fillStyle='#000';if(f.run.sewerHatch)g.fillRect(DW.SEWER.extensionStart,DW.SEWER.roofY,DW.SEWER.exit-DW.SEWER.extensionStart,DW.SEWER.deepFloorY-DW.SEWER.roofY+160);if(f.run.sewerHatch){g.fillStyle='#596553';g.fillRect(DW.HOSPITAL.start,250,DW.HOSPITAL.end-DW.HOSPITAL.start,190);g.fillStyle='#677365';g.fillRect(DW.HOSPITAL.start,440,DW.HOSPITAL.end-DW.HOSPITAL.start,450);}g.globalCompositeOperation='lighter';const all=sources(f),visible=all.filter(l=>l.x+l.r>f.left&&l.x-l.r<f.right&&l.y+l.r> -f.offset/f.zoom&&l.y-l.r<(f.height-f.offset)/f.zoom).sort((a,b)=>(b.id.startsWith('muzzle')?100:b.id.startsWith('torch')?60:0)-(a.id.startsWith('muzzle')?100:a.id.startsWith('torch')?60:0)||Math.abs(a.x-(f.left+f.right)/2)-Math.abs(b.x-(f.left+f.right)/2)).slice(0,preset.lights),boxes=geometry(f,visible,preset);stats.shadows=0;stats.cacheHits=0;const meshes=[];
 for(const l of visible){const relevant=boxes.filter(b=>!b.dynamic),edges=segments(relevant,l),key=l.id+':'+Math.round(l.x)+':'+Math.round(l.y)+':'+Math.round(l.r/4)+':'+edges.map(e=>e[0].join(',')).join(';');let polygon=cache.get(key);if(polygon)stats.cacheHits++;else{polygon=mesh(l,edges,preset.rays);cache.set(key,polygon);if(cache.size>96)cache.delete(cache.keys().next().value);}const actorEdges=segments(boxes.filter(b=>b.dynamic),l);if(actorEdges.length)polygon=mesh(l,[...edges,...actorEdges],preset.rays);stats.shadows+=boxes.filter(b=>!b.receiverOnly&&b.id!==l.emitter&&b.x<l.x+l.r&&b.x+b.w>l.x-l.r&&b.y<l.y+l.r&&b.y+b.h>l.y-l.r).length;meshes.push({l,polygon});if(preset.soft){const samples=preset.soft===2?3:2;for(let i=0;i<samples;i++){const originalX=l.x;l.x+=i===0?-2:2;const softKey=key+':soft-'+i;let p=cache.get(softKey);if(!p){p=mesh(l,edges,preset.rays);cache.set(softKey,p);if(cache.size>96)cache.delete(cache.keys().next().value);}if(actorEdges.length)p=mesh(l,[...edges,...actorEdges],preset.rays);irradiance(l,p,1/samples);l.x=originalX;}}else irradiance(l,polygon);}
 // Receiver meshes keep the lit face of a solid object visible while its
 // projected shadow remains on the world behind it. Only nearby visible meshes.
 for(const {l} of meshes)for(const b of boxes){if(b.id.startsWith('floor')||b.id.startsWith('step')||b.x+b.w<f.left||b.x>f.right||!receives(l,b,boxes))continue;const polygon=b.points||[[b.x,b.y],[b.x+b.w,b.y],[b.x+b.w,b.y+b.h],[b.x,b.y+b.h]];if(DeadwalkEnvironment.detailed(b.x))directionalReceiver(l,b,polygon);else irradiance(l,polygon,b.dynamic?.58:.4);}
 // Multiply the world's albedo by a coloured, geometry-clipped light field.
 ctx.save();ctx.setTransform(f.dpr,0,0,f.dpr,0,0);ctx.globalCompositeOperation='multiply';ctx.imageSmoothingEnabled=true;ctx.drawImage(field,0,0,f.width,f.height);ctx.globalCompositeOperation='screen';for(const {l} of meshes){const x=(l.x-f.left)*f.zoom,y=l.y*f.zoom+f.offset,r=l.id.startsWith('torch')?8:l.id.startsWith('fire')?18:12;const glow=ctx.createRadialGradient(x,y,1,x,y,r);glow.addColorStop(0,`rgba(${l.color.join(',')},.23)`);glow.addColorStop(1,`rgba(${l.color.join(',')},0)`);ctx.fillStyle=glow;ctx.fillRect(x-r,y-r,r*2,r*2);}ctx.save();ctx.setTransform(f.dpr*f.zoom,0,0,f.dpr*f.zoom,-f.left*f.dpr*f.zoom,f.offset*f.dpr);ctx.globalCompositeOperation='screen';for(const {l,polygon} of meshes){if(!l.id.startsWith('torch')&&!l.id.startsWith('lamp'))continue;if(quality==='low')continue;ctx.save();ctx.beginPath();polygon.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.clip();const haze=ctx.createRadialGradient(l.x,l.y,0,l.x,l.y,l.r);haze.addColorStop(0,'#e1ddd008');haze.addColorStop(1,'#e1ddd000');ctx.fillStyle=haze;ctx.beginPath();ctx.moveTo(l.x,l.y);ctx.arc(l.x,l.y,l.r,l.angle-l.cone,l.angle+l.cone);ctx.closePath();ctx.fill();for(let i=0;i<16;i++){const d=18+(i*47+f.time*4)%(l.r*.83),side=Math.sin(i*17+f.time*.12)*d*(l.id.startsWith('lamp')?.52:.19);const x=l.x+Math.cos(l.angle)*d-Math.sin(l.angle)*side,y=l.y+Math.sin(l.angle)*d+Math.cos(l.angle)*side;ctx.fillStyle='#cecdb633';ctx.fillRect(x,y,.75,.75);}ctx.restore();}reflections(ctx,f,meshes);ctx.restore();const vignette=ctx.createRadialGradient(f.width/2,f.height*.55,f.width*.24,f.width/2,f.height*.55,f.width*.67);vignette.addColorStop(0,'#02071100');vignette.addColorStop(1,'#02071124');ctx.globalCompositeOperation='multiply';ctx.fillStyle=vignette;ctx.fillRect(0,0,f.width,f.height);ctx.restore();stats.lights=visible.length;stats.casters=boxes.filter(b=>!b.receiverOnly).length;stats.quality=quality;stats.renderMs=performance.now()-start;
 if(debug)drawDebug(ctx,f,meshes,boxes);for(const l of all)pool.push(l);}
 function drawDebug(ctx,f,meshes,boxes){ctx.save();ctx.setTransform(f.dpr*f.zoom,0,0,f.dpr*f.zoom,-f.left*f.dpr*f.zoom,f.offset*f.dpr);ctx.lineWidth=1/f.zoom;for(const b of boxes){ctx.strokeStyle=b.dynamic?'#fd8c6a':'#5ee6ac';if(b.points){ctx.beginPath();b.points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.stroke();}else ctx.strokeRect(b.x,b.y,b.w,b.h);}for(const {l,polygon} of meshes){ctx.strokeStyle=`rgba(${l.color.join(',')},.4)`;ctx.beginPath();ctx.arc(l.x,l.y,l.r,0,Math.PI*2);ctx.stroke();ctx.beginPath();polygon.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.stroke();ctx.fillStyle=`rgb(${l.color.join(',')})`;ctx.fillRect(l.x-3,l.y-3,6,6);if(l.angle!==null)for(const angle of [l.angle-l.cone,l.angle,l.angle+l.cone]){ctx.beginPath();ctx.moveTo(l.x,l.y);ctx.lineTo(l.x+Math.cos(angle)*l.r,l.y+Math.sin(angle)*l.r);ctx.stroke();}}ctx.restore();ctx.save();ctx.setTransform(f.dpr,0,0,f.dpr,0,0);ctx.fillStyle='#071317e8';ctx.fillRect(18,218,390,65);ctx.fillStyle='#d6f3b2';ctx.font='12px monospace';ctx.fillText(`LIGHTING ${quality.toUpperCase()} · ${stats.renderMs.toFixed(1)} ms`,28,238);ctx.fillText(`${stats.lights} lights · ${stats.casters} casters · ${stats.shadows} shadows`,28,255);ctx.fillText(`${stats.cacheHits} static mesh cache hits · F3: debug`,28,273);ctx.restore();}
 const perceptionCache=new WeakMap();
 function visibleTo(run,observer,target){const o=DW.weaponOrigin(observer),tx=target.x,ty=target.y-40,distance=Math.hypot(tx-o.x,ty-o.y),delta=Math.atan2(Math.sin(Math.atan2(ty-o.y,tx-o.x)-o.angle),Math.cos(Math.atan2(ty-o.y,tx-o.x)-o.angle));if(distance>900||Math.abs(delta)>.85||!run.clearLane(o.x,o.y,tx,ty))return false;const stamp=Math.floor(run.time*8)+':'+run.safeRooms.map(r=>Number(r.entryOpen)+2*Number(r.exitOpen)).join(',');let frame=perceptionCache.get(run);if(!frame||frame.stamp!==stamp){const f={run,time:run.time,left:Math.min(...run.players.map(p=>p.x))-1600,right:Math.max(...run.players.map(p=>p.x))+1600,perception:true},all=sources(f),lights=all.map(l=>({...l}));for(const l of all)pool.push(l);frame={stamp,lights,boxes:geometry(f,lights,{actors:0})};perceptionCache.set(run,frame);}const receiver={id:'sight-target',x:tx-10,y:target.y-58,w:20,h:45};for(const l of frame.lights){const d=Math.hypot(tx-l.x,ty-l.y);if(d>=l.r)continue;let energy=l.strength*Math.pow(1-d/l.r,1.35);if(l.angle!==null){const off=Math.abs(Math.atan2(Math.sin(Math.atan2(ty-l.y,tx-l.x)-l.angle),Math.cos(Math.atan2(ty-l.y,tx-l.x)-l.angle)));if(off>l.cone)continue;energy*=Math.pow(Math.max(0,1-Math.pow(off/l.cone,2)),2);}if(energy>=.13&&receives(l,receiver,frame.boxes))return true;}return false;}
 function setQuality(value){if(!presets[value])return;quality=value;cache.clear();try{localStorage.setItem('deadwalk-light-quality',value);}catch{}}
 function settings(){for(const panel of document.querySelectorAll('.overlay .panel')){const host=document.createElement('details');host.className='controller-settings';const title=document.createElement('summary');title.textContent='LIGHTING SETTINGS';host.append(title);for(const [labelText,options] of [['Light quality',{low:'Low',medium:'Medium',high:'High',ultra:'Ultra'}],['Lighting debug',{off:'Off',on:'On'}]]){const label=document.createElement('label');label.textContent=labelText;const select=document.createElement('select');select.setAttribute('aria-label',labelText);select.dataset.graphics=labelText==='Light quality'?'quality':'debug';for(const [value,text] of Object.entries(options)){const option=document.createElement('option');option.value=value;option.textContent=text;select.append(option);}select.value=select.dataset.graphics==='quality'?quality:'off';select.onchange=()=>{if(select.dataset.graphics==='quality')setQuality(select.value);else debug=select.value==='on';for(const other of document.querySelectorAll(`[data-graphics="${select.dataset.graphics}"]`))other.value=select.value;};label.append(select);host.append(label);}const help=document.createElement('p');help.textContent='Lower quality reduces light resolution, shadow detail and active lights. F3 shows light geometry and timing.';host.append(help);panel.append(host);}}
 addEventListener('keydown',e=>{if(e.code==='F3'&&!e.repeat){e.preventDefault();debug=!debug;for(const select of document.querySelectorAll('[data-graphics="debug"]'))select.value=debug?'on':'off';}});
 return {visibleTo,render,setQuality,settings,presets,stats,field,mesh,sources,get quality(){return quality;},get debug(){return debug;}};
})();
